#contains the namespace of the robots we want to control
ypp: false
    # name: sphero_ypp
    # address: 68:86:E7:09:0B:77
rwp: false
rgo: false
pob: false
www: false
rpg: false
wwb: false
gbr: false
www: false
yry: true
